export const TEST_IDS = {
  shell: {
    toolbar: 'app-toolbar',
    projectSwitcherButton: 'project-switcher-button',
    projectSwitcherMenu: 'project-switcher-menu',
    addProjectButton: 'add-project-button',
    projectDropdownAddButton: 'project-dropdown-add-button',
    githubPanelButton: 'github-panel-button',
    settingsButton: 'settings-button',
    terminalArea: 'terminal-area',
    terminalGrid: 'terminal-grid',
  },
  emptyState: {
    project: 'project-empty-state',
    terminal: 'terminal-empty-state',
  },
  terminal: {
    actionBar: 'terminal-action-bar',
    countLabel: 'terminal-count-label',
    newTerminalButton: 'new-terminal-button',
    yoloToggleButton: 'toggle-yolo-button',
    killAllButton: 'kill-all-button',
    killAllDialog: 'kill-all-confirm-dialog',
    killAllCancelButton: 'kill-all-cancel-button',
    killAllConfirmButton: 'kill-all-confirm-button',
  },
  panel: {
    github: 'github-panel',
    githubEmptyState: 'github-panel-empty-state',
    githubSummary: 'github-panel-summary',
    githubTabs: 'github-panel-tabs',
    githubTabChanges: 'github-panel-tab-changes',
    githubTabHistory: 'github-panel-tab-history',
    githubTabGitHub: 'github-panel-tab-github',
    githubTabPanelChanges: 'github-panel-tabpanel-changes',
    githubTabPanelHistory: 'github-panel-tabpanel-history',
    githubTabPanelGitHub: 'github-panel-tabpanel-github',
    settings: 'settings-panel',
    settingsCloseButton: 'settings-close-button',
    settingsCancelButton: 'settings-cancel-button',
    settingsSaveButton: 'settings-save-button',
  },
} as const
